version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8188:8080
    volumes:
      - /:/data
      - ./config:/config
    restart: unless-stopped
