version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
